// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import (
	models "github.com/VolunteerOne/volunteer-one-app/backend/models"
	mock "github.com/stretchr/testify/mock"
)

// CommentsRepository is an autogenerated mock type for the CommentsRepository type
type CommentsRepository struct {
	mock.Mock
}

// AllComments provides a mock function with given fields:
func (_m *CommentsRepository) AllComments() ([]models.Comments, error) {
	ret := _m.Called()

	var r0 []models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Comments, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Comments); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comments)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateComment provides a mock function with given fields: Comment
func (_m *CommentsRepository) CreateComment(Comment models.Comments) (models.Comments, error) {
	ret := _m.Called(Comment)

	var r0 models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Comments) (models.Comments, error)); ok {
		return rf(Comment)
	}
	if rf, ok := ret.Get(0).(func(models.Comments) models.Comments); ok {
		r0 = rf(Comment)
	} else {
		r0 = ret.Get(0).(models.Comments)
	}

	if rf, ok := ret.Get(1).(func(models.Comments) error); ok {
		r1 = rf(Comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteComment provides a mock function with given fields: Comment
func (_m *CommentsRepository) DeleteComment(Comment models.Comments) error {
	ret := _m.Called(Comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Comments) error); ok {
		r0 = rf(Comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditComment provides a mock function with given fields: Comment
func (_m *CommentsRepository) EditComment(Comment models.Comments) (models.Comments, error) {
	ret := _m.Called(Comment)

	var r0 models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Comments) (models.Comments, error)); ok {
		return rf(Comment)
	}
	if rf, ok := ret.Get(0).(func(models.Comments) models.Comments); ok {
		r0 = rf(Comment)
	} else {
		r0 = ret.Get(0).(models.Comments)
	}

	if rf, ok := ret.Get(1).(func(models.Comments) error); ok {
		r1 = rf(Comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindComment provides a mock function with given fields: id
func (_m *CommentsRepository) FindComment(id string) (models.Comments, error) {
	ret := _m.Called(id)

	var r0 models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Comments, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Comments); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Comments)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommentsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentsRepository creates a new instance of CommentsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentsRepository(t mockConstructorTestingTNewCommentsRepository) *CommentsRepository {
	mock := &CommentsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
