// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// CommentsController is an autogenerated mock type for the CommentsController type
type CommentsController struct {
	mock.Mock
}

// AllComments provides a mock function with given fields: c
func (_m *CommentsController) AllComments(c *gin.Context) {
	_m.Called(c)
}

// CreateComment provides a mock function with given fields: c
func (_m *CommentsController) CreateComment(c *gin.Context) {
	_m.Called(c)
}

// DeleteComment provides a mock function with given fields: c
func (_m *CommentsController) DeleteComment(c *gin.Context) {
	_m.Called(c)
}

// EditComment provides a mock function with given fields: c
func (_m *CommentsController) EditComment(c *gin.Context) {
	_m.Called(c)
}

// FindComment provides a mock function with given fields: c
func (_m *CommentsController) FindComment(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewCommentsController interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentsController creates a new instance of CommentsController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentsController(t mockConstructorTestingTNewCommentsController) *CommentsController {
	mock := &CommentsController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
