// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	models "github.com/VolunteerOne/volunteer-one-app/backend/models"
	mock "github.com/stretchr/testify/mock"
)

// CommentsService is an autogenerated mock type for the CommentsService type
type CommentsService struct {
	mock.Mock
}

// AllComments provides a mock function with given fields:
func (_m *CommentsService) AllComments() ([]models.Comments, error) {
	ret := _m.Called()

	var r0 []models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Comments, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Comments); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comments)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateComment provides a mock function with given fields: comment
func (_m *CommentsService) CreateComment(comment models.Comments) (models.Comments, error) {
	ret := _m.Called(comment)

	var r0 models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Comments) (models.Comments, error)); ok {
		return rf(comment)
	}
	if rf, ok := ret.Get(0).(func(models.Comments) models.Comments); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(models.Comments)
	}

	if rf, ok := ret.Get(1).(func(models.Comments) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteComment provides a mock function with given fields: comment
func (_m *CommentsService) DeleteComment(comment models.Comments) error {
	ret := _m.Called(comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Comments) error); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditComment provides a mock function with given fields: comment
func (_m *CommentsService) EditComment(comment models.Comments) (models.Comments, error) {
	ret := _m.Called(comment)

	var r0 models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Comments) (models.Comments, error)); ok {
		return rf(comment)
	}
	if rf, ok := ret.Get(0).(func(models.Comments) models.Comments); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(models.Comments)
	}

	if rf, ok := ret.Get(1).(func(models.Comments) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindComment provides a mock function with given fields: id
func (_m *CommentsService) FindComment(id string) (models.Comments, error) {
	ret := _m.Called(id)

	var r0 models.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Comments, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Comments); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Comments)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommentsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentsService creates a new instance of CommentsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentsService(t mockConstructorTestingTNewCommentsService) *CommentsService {
	mock := &CommentsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
