// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// EventController is an autogenerated mock type for the EventController type
type EventController struct {
	mock.Mock
}

// All provides a mock function with given fields: _a0
func (_m *EventController) All(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Create provides a mock function with given fields: _a0
func (_m *EventController) Create(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Delete provides a mock function with given fields: _a0
func (_m *EventController) Delete(_a0 *gin.Context) {
	_m.Called(_a0)
}

// One provides a mock function with given fields: _a0
func (_m *EventController) One(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Update provides a mock function with given fields: _a0
func (_m *EventController) Update(_a0 *gin.Context) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewEventController interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventController creates a new instance of EventController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventController(t mockConstructorTestingTNewEventController) *EventController {
	mock := &EventController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
