// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// FriendController is an autogenerated mock type for the FriendController type
type FriendController struct {
	mock.Mock
}

// Accept provides a mock function with given fields: c
func (_m *FriendController) Accept(c *gin.Context) {
	_m.Called(c)
}

// All provides a mock function with given fields: c
func (_m *FriendController) All(c *gin.Context) {
	_m.Called(c)
}

// Create provides a mock function with given fields: c
func (_m *FriendController) Create(c *gin.Context) {
	_m.Called(c)
}

// One provides a mock function with given fields: c
func (_m *FriendController) One(c *gin.Context) {
	_m.Called(c)
}

// Reject provides a mock function with given fields: c
func (_m *FriendController) Reject(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewFriendController interface {
	mock.TestingT
	Cleanup(func())
}

// NewFriendController creates a new instance of FriendController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFriendController(t mockConstructorTestingTNewFriendController) *FriendController {
	mock := &FriendController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
