// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	models "github.com/VolunteerOne/volunteer-one-app/backend/models"
	mock "github.com/stretchr/testify/mock"
)

// LikesService is an autogenerated mock type for the LikesService type
type LikesService struct {
	mock.Mock
}

// AllLikes provides a mock function with given fields:
func (_m *LikesService) AllLikes() ([]models.Likes, error) {
	ret := _m.Called()

	var r0 []models.Likes
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Likes, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Likes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Likes)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLike provides a mock function with given fields: like
func (_m *LikesService) CreateLike(like models.Likes) (models.Likes, error) {
	ret := _m.Called(like)

	var r0 models.Likes
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Likes) (models.Likes, error)); ok {
		return rf(like)
	}
	if rf, ok := ret.Get(0).(func(models.Likes) models.Likes); ok {
		r0 = rf(like)
	} else {
		r0 = ret.Get(0).(models.Likes)
	}

	if rf, ok := ret.Get(1).(func(models.Likes) error); ok {
		r1 = rf(like)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLike provides a mock function with given fields: like
func (_m *LikesService) DeleteLike(like models.Likes) error {
	ret := _m.Called(like)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Likes) error); ok {
		r0 = rf(like)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindLike provides a mock function with given fields: id
func (_m *LikesService) FindLike(id string) (models.Likes, error) {
	ret := _m.Called(id)

	var r0 models.Likes
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Likes, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Likes); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Likes)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLikes provides a mock function with given fields: id
func (_m *LikesService) GetLikes(id string) (int64, error) {
	ret := _m.Called(id)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewLikesService interface {
	mock.TestingT
	Cleanup(func())
}

// NewLikesService creates a new instance of LikesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLikesService(t mockConstructorTestingTNewLikesService) *LikesService {
	mock := &LikesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
