// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MessagesController is an autogenerated mock type for the MessagesController type
type MessagesController struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: c
func (_m *MessagesController) CreateMessage(c *gin.Context) {
	_m.Called(c)
}

// DeleteMessage provides a mock function with given fields: c
func (_m *MessagesController) DeleteMessage(c *gin.Context) {
	_m.Called(c)
}

// FindMessage provides a mock function with given fields: c
func (_m *MessagesController) FindMessage(c *gin.Context) {
	_m.Called(c)
}

// ListAllMessagesForUser provides a mock function with given fields: c
func (_m *MessagesController) ListAllMessagesForUser(c *gin.Context) {
	_m.Called(c)
}

// UpdateMessageReadStatus provides a mock function with given fields: c
func (_m *MessagesController) UpdateMessageReadStatus(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewMessagesController interface {
	mock.TestingT
	Cleanup(func())
}

// NewMessagesController creates a new instance of MessagesController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMessagesController(t mockConstructorTestingTNewMessagesController) *MessagesController {
	mock := &MessagesController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
