// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// OrganizationController is an autogenerated mock type for the OrganizationController type
type OrganizationController struct {
	mock.Mock
}

// All provides a mock function with given fields: _a0
func (_m *OrganizationController) All(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Create provides a mock function with given fields: _a0
func (_m *OrganizationController) Create(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Delete provides a mock function with given fields: _a0
func (_m *OrganizationController) Delete(_a0 *gin.Context) {
	_m.Called(_a0)
}

// One provides a mock function with given fields: _a0
func (_m *OrganizationController) One(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Update provides a mock function with given fields: _a0
func (_m *OrganizationController) Update(_a0 *gin.Context) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewOrganizationController interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrganizationController creates a new instance of OrganizationController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrganizationController(t mockConstructorTestingTNewOrganizationController) *OrganizationController {
	mock := &OrganizationController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
