// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// OrgUsersController is an autogenerated mock type for the OrgUsersController type
type OrgUsersController struct {
	mock.Mock
}

// CreateOrgUser provides a mock function with given fields: c
func (_m *OrgUsersController) CreateOrgUser(c *gin.Context) {
	_m.Called(c)
}

// DeleteOrgUser provides a mock function with given fields: c
func (_m *OrgUsersController) DeleteOrgUser(c *gin.Context) {
	_m.Called(c)
}

// FindOrgUser provides a mock function with given fields: c
func (_m *OrgUsersController) FindOrgUser(c *gin.Context) {
	_m.Called(c)
}

// ListAllOrgUsers provides a mock function with given fields: c
func (_m *OrgUsersController) ListAllOrgUsers(c *gin.Context) {
	_m.Called(c)
}

// UpdateOrgUser provides a mock function with given fields: c
func (_m *OrgUsersController) UpdateOrgUser(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewOrgUsersController interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrgUsersController creates a new instance of OrgUsersController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrgUsersController(t mockConstructorTestingTNewOrgUsersController) *OrgUsersController {
	mock := &OrgUsersController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
