// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	models "github.com/VolunteerOne/volunteer-one-app/backend/models"
	mock "github.com/stretchr/testify/mock"
)

// PostsRepository is an autogenerated mock type for the PostsRepository type
type PostsRepository struct {
	mock.Mock
}

// AllPosts provides a mock function with given fields:
func (_m *PostsRepository) AllPosts() ([]models.Posts, error) {
	ret := _m.Called()

	var r0 []models.Posts
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Posts, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Posts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Posts)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePost provides a mock function with given fields: post
func (_m *PostsRepository) CreatePost(post models.Posts) (models.Posts, error) {
	ret := _m.Called(post)

	var r0 models.Posts
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Posts) (models.Posts, error)); ok {
		return rf(post)
	}
	if rf, ok := ret.Get(0).(func(models.Posts) models.Posts); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Get(0).(models.Posts)
	}

	if rf, ok := ret.Get(1).(func(models.Posts) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePost provides a mock function with given fields: post
func (_m *PostsRepository) DeletePost(post models.Posts) error {
	ret := _m.Called(post)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Posts) error); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditPost provides a mock function with given fields: post
func (_m *PostsRepository) EditPost(post models.Posts) (models.Posts, error) {
	ret := _m.Called(post)

	var r0 models.Posts
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Posts) (models.Posts, error)); ok {
		return rf(post)
	}
	if rf, ok := ret.Get(0).(func(models.Posts) models.Posts); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Get(0).(models.Posts)
	}

	if rf, ok := ret.Get(1).(func(models.Posts) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPost provides a mock function with given fields: id
func (_m *PostsRepository) FindPost(id string) (models.Posts, error) {
	ret := _m.Called(id)

	var r0 models.Posts
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Posts, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Posts); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Posts)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPostsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostsRepository creates a new instance of PostsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostsRepository(t mockConstructorTestingTNewPostsRepository) *PostsRepository {
	mock := &PostsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
