// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// PostsController is an autogenerated mock type for the PostsController type
type PostsController struct {
	mock.Mock
}

// AllPosts provides a mock function with given fields: c
func (_m *PostsController) AllPosts(c *gin.Context) {
	_m.Called(c)
}

// CreatePost provides a mock function with given fields: c
func (_m *PostsController) CreatePost(c *gin.Context) {
	_m.Called(c)
}

// DeletePost provides a mock function with given fields: c
func (_m *PostsController) DeletePost(c *gin.Context) {
	_m.Called(c)
}

// EditPost provides a mock function with given fields: c
func (_m *PostsController) EditPost(c *gin.Context) {
	_m.Called(c)
}

// FindPost provides a mock function with given fields: c
func (_m *PostsController) FindPost(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewPostsController interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostsController creates a new instance of PostsController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostsController(t mockConstructorTestingTNewPostsController) *PostsController {
	mock := &PostsController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
