// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	models "github.com/VolunteerOne/volunteer-one-app/backend/models"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// Bind provides a mock function with given fields: _a0, _a1
func (_m *UsersService) Bind(_a0 *gin.Context, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: user
func (_m *UsersService) CreateUser(user models.Users) (models.Users, error) {
	ret := _m.Called(user)

	var r0 models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Users) (models.Users, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.Users) models.Users); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.Users)
	}

	if rf, ok := ret.Get(1).(func(models.Users) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: user
func (_m *UsersService) DeleteUser(user models.Users) (models.Users, error) {
	ret := _m.Called(user)

	var r0 models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Users) (models.Users, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.Users) models.Users); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.Users)
	}

	if rf, ok := ret.Get(1).(func(models.Users) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HashPassword provides a mock function with given fields: password
func (_m *UsersService) HashPassword(password []byte) ([]byte, error) {
	ret := _m.Called(password)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OneUser provides a mock function with given fields: id, user
func (_m *UsersService) OneUser(id string, user models.Users) (models.Users, error) {
	ret := _m.Called(id, user)

	var r0 models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(string, models.Users) (models.Users, error)); ok {
		return rf(id, user)
	}
	if rf, ok := ret.Get(0).(func(string, models.Users) models.Users); ok {
		r0 = rf(id, user)
	} else {
		r0 = ret.Get(0).(models.Users)
	}

	if rf, ok := ret.Get(1).(func(string, models.Users) error); ok {
		r1 = rf(id, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: user
func (_m *UsersService) UpdateUser(user models.Users) (models.Users, error) {
	ret := _m.Called(user)

	var r0 models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Users) (models.Users, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.Users) models.Users); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.Users)
	}

	if rf, ok := ret.Get(1).(func(models.Users) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsersService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersService(t mockConstructorTestingTNewUsersService) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
