# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/VolunteerOne/volunteer-one-app

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
        env:
          GOPATH: /home/runner/work/volunteer-one-app/go

      - name: Build
        run: |
          pwd
          cd backend
          go mod download
          go build -v ./...
        env:
          GOPATH: /home/runner/work/volunteer-one-app/go

      - name: Test
        run: go test -v ./...
        env:
          GOPATH: /home/runner/work/volunteer-one-app/go
